# Generated by Django 4.1.4 on 2022-12-26 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Markets',
            new_name='Market',
        ),
    ]
