# Generated by Django 4.1.4 on 2022-12-26 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0002_rename_markets_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tabdeal',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='tabdeal',
            name='api_secret',
        ),
        migrations.RemoveField(
            model_name='tabdeal',
            name='created',
        ),
        migrations.RemoveField(
            model_name='tabdeal',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tabdeal',
            name='markets',
        ),
        migrations.RemoveField(
            model_name='tabdeal',
            name='updated',
        ),
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
                ('markets', models.ManyToManyField(related_name='exchanges', to='trading_bot.market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='tabdeal',
            name='exchange_ptr',
            field=models.OneToOneField(auto_created=True, default=None, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading_bot.exchange'),
            preserve_default=False,
        ),
    ]
