# Generated by Django 4.1.4 on 2022-12-27 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0003_remove_tabdeal_api_key_remove_tabdeal_api_secret_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('api_key', models.CharField(max_length=255)),
                ('api_secret', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('investment', models.DecimalField(decimal_places=8, max_digits=32)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.account')),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.market')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=32)),
                ('side', models.SmallIntegerField(choices=[(1, 'Buy'), (2, 'Sell')])),
                ('state', models.SmallIntegerField(choices=[(1, 'Waitingtosubmit'), (2, 'Waiting'), (3, 'Partiallyfilled'), (4, 'Partiallyfilledandfinished'), (5, 'Filled'), (6, 'Canceled'), (7, 'Error')], default=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='exchange',
            name='api_secret',
        ),
        migrations.CreateModel(
            name='GridBot',
            fields=[
                ('bot_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trading_bot.bot')),
                ('no_grid_lines', models.IntegerField()),
                ('upper_price', models.DecimalField(decimal_places=8, max_digits=32)),
                ('lower_price', models.DecimalField(decimal_places=8, max_digits=32)),
            ],
            options={
                'abstract': False,
            },
            bases=('trading_bot.bot',),
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.order')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='order',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.exchange'),
        ),
        migrations.AddField(
            model_name='account',
            name='exchange',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.exchange'),
        ),
        migrations.AddField(
            model_name='order',
            name='grid_bot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trading_bot.gridbot'),
        ),
    ]
