# Generated by Django 4.1.4 on 2022-12-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0004_account_bot_order_remove_exchange_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exchange',
            name='name',
            field=models.CharField(default='tabdeal', max_length=256),
            preserve_default=False,
        ),
    ]
