# Generated by Django 4.1.4 on 2022-12-27 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0006_gridbot_active_order_account_order_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='market',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='trading_bot.market'),
            preserve_default=False,
        ),
    ]
