# Generated by Django 4.1.4 on 2022-12-27 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0007_order_market'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='name',
        ),
        migrations.AddField(
            model_name='exchange',
            name='exchange_provider',
            field=models.SmallIntegerField(choices=[(1, 'Tabdeal')], default=1, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Tabdeal',
        ),
    ]
