# Generated by Django 4.1.4 on 2022-12-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0008_remove_exchange_name_exchange_exchange_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='precision',
            field=models.IntegerField(default=8),
        ),
    ]
