# Generated by Django 4.1.4 on 2022-12-27 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_bot', '0009_currency_precision'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='remote_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.SmallIntegerField(choices=[(1, 'Waitingtosubmit'), (2, 'Waiting'), (3, 'Partiallyfilled'), (4, 'Partiallyfilledandfinished'), (5, 'Filled'), (6, 'Canceled'), (7, 'Error'), (8, 'Idle')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('remote_id', 'exchange')},
        ),
    ]
